name: Deploy Python Application

on:
  push:
    branches:
      - main  # 或者你想要触发部署的分支名
  schedule:
    - cron: "0 5 * * *"  # 每天北京时间下午1点（UTC+8）执行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: python main.py

    - name: Run push.py
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # 引用 GitHub Secret
      run: python push.py