name: Deploy Python Application

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"  # 每天北京时间下午4点（UTC+8）执行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and Run script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
